# Generated by Django 3.2.8 on 2021-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('ic_no', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='IcNo')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
            ],
        ),
    ]
